apiVersion: v1
kind: Pod
metadata:
  name: hacker
  labels:
    group: arpspoof
spec:
  containers:
  - name: hacker
    image: timwang/ieeetrycybsecurity:11.0
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
